site_name: Curso de Matemática Básica
docs_dir: aulas
repo_url: https://github.com/ivansantiagojr/curso-matematica-basica
repo_name: ivansantiagojr/curso-matematica-basica
edit_uri: tree/main/aulas
theme:
  name: material
  language: pt-BR
  features:
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - scheme: slate
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Modo claro
    - scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Modo noturno
markdown_extensions:
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.keys
  - footnotes
  - admonition
  - markdown.extensions.attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
plugins:
  - glightbox
  - mkdocs-video
  - search:
      lang: pt
  - git-authors:
      show_email_address: false
      show_line_count: true
  - git-revision-date-localized
  - social
  - with-pdf:
      author: Ivan Santiago
      cover_title: Matemática Básica para Adultos
      copyright: CC BY-NC-SA
      toc_level: 6
      enabled_if_env: ENABLE_PDF_EXPORT
      toc_title: Índice
extra_css:
  - stylesheets/extra.css
