[tool.poetry]
name = "curso-matematica-basica"
version = "0.1.0"
description = ""
authors = [
    "ivansantiagojr <ivansantiago.junior@gmail.com>",
]
readme = "README.md"
packages = [{ include = "curso-matematica-basica" }]

[tool.poetry.dependencies]
python = "^3.11"
mkdocs = "^1.4.3"
mkdocs-material = "^9.5.1"
taskipy = "^1.11.0"
mkdocs-glightbox = "^0.3.4"
mkdocs-video = "^1.5.0"
mkdocs-git-authors-plugin = "^0.7.2"
mkdocs-git-revision-date-localized-plugin = "^1.2.0"
pillow = "^10.0.0"
cairosvg = "^2.7.0"
mkdocs-with-pdf = "^0.9.3"

[tool.taskipy.tasks]
serve = "mkdocs serve --dev-addr localhost:8080"
deploy = "mkdocs gh-deploy"
slides = "marp -I slides/brutos/ --html --theme slides/brutos/rose-pine.css --allow-local-files --pdf -o slides/pdf/"
slides_html = "marp -I slides/brutos --html --theme slides/brutos/rose-pine.css --allow-local-files -o slides/html"
pdf = "ENABLE_PDF_EXPORT=1 mkdocs build"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
